name: Dispatch v1.1.0

on:
  push:
    branches: [main]

permissions:
  actions: write
  contents: read

jobs:
  dispatch:
    if: "github.event.head_commit.message == 'ci: dispatch v1.1.0 build'"
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Build
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run build.yml --ref v1.1.0
